name: Update Cache

on:
  schedule:
    - cron: '0 0 * * *'  # 매일 자정 (UTC 기준, KST는 +9시간)
  workflow_dispatch:      # 수동 트리거 가능

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run crawling script
        run: python scripts/crawl.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add data/*.json
          git commit -m "Update cached data [$(date +'%Y-%m-%d %H:%M:%S')]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
